name: Tree Check

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  ensure-core-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure LICENSE
        run: test -f "LICENSE"

      - name: Ensure README
        run: test -f "README.md"

  ensure-legalease:
    runs-on: ubuntu-latest
    
    needs: ensure-core-files
    
    steps:
      - uses: actions/checkout@v2

      - name: Copyright
        run: grep "&copy;" README.md

      - name: Liability
        run: grep "Liability" README.md

  ensure-git-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure .gitignore
        run: test -f ".gitignore"
