name: Tree Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  ensure-core-files:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure README
        run: test ! -f "README.md"

      - name: Ensure LICENSE
        run: test ! -f "LICENSE"

      - name: Ensure .gitignore
        run: test ! -f ".gitignore"

  ensure-legalease:
    
    runs-on: ubuntu-latest
    steps:
      - name: Copyright
        run: grep "@copy;" README.md
